{% set name = "dj-rest-auth" %}
{% set version = "2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dj-rest-auth-{{ version }}.tar.gz
  sha256: f292f3dffb8fc896da10adf47e94a254fb8bf42e672a066e63566363d764ad42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django >=2.0
    - djangorestframework >=3.7.0
    - python >=3.5
  run_constrained:
    - django-allauth >=0.40.0,<0.48.0

test:
  imports:
    - dj_rest_auth
    - dj_rest_auth.registration
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/iMerica/dj-rest-auth
  summary: Authentication and Registration in Django Rest Framework
  license: MIT
  license_file: LICENSE
  doc_url: https://dj-rest-auth.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
